stages:
  - docker-build
before_script:
  - aliimage=registry.docker.quancheng-ec.com:5000
  - hostname -i
  - whoami
build_image:
  stage: docker-build
  
  script:
    - echo `git rev-parse --short HEAD` >> bin/git.tag
    - echo $image
    - cd collector
    - mvn clean package docker:build -DskipTests
    - docker push $aliimage/pinpoint-collector:1.6.1-SNAPSHOT
    - cd ..
    - cd web
    - mvn clean package docker:build -DskipTests
    - docker push $aliimage/pinpoint-web:1.6.1-SNAPSHOT
  only:
    - master