stages:
  - docker-build
before_script:
  - aliimage=registry.docker.quancheng-ec.com:5000
  - hostname -i
  - whoami
build_image:
  stage: docker-build
  
  script:
    - mvn clean install -Dmaven.test.skip=true
    - cd collector
    - mvn clean package docker:build -DskipTests
    - docker push $aliimage/pinpoint-collector:1.6.1
    - cd ..
    - cd web
    - mvn clean package docker:build -DskipTests
    - docker push $aliimage/pinpoint-web:1.6.1
  only:
    - master