stages:
  - docker-build
before_script:
  - aliimage=registry.docker.quancheng-ec.com:5000
build_image:
  stage: docker-build
  
  script:
    - mvn clean install -Dmaven.test.skip=true
    - cd agent/target/
    - curl -I --user 'liushiming:Hello899' -X  DELETE http://repo.quancheng-ec.com/repository/documentation/pinpoint-agent-1.6.1-SNAPSHOT.zip
    - curl -v --user 'liushiming:Hello899' --upload-file pinpoint-agent-1.6.1-SNAPSHOT.zip http://repo.quancheng-ec.com/repository/documentation/
    - cd ../..
    - cd collector
    - mvn clean package docker:build -DskipTests
    - docker push $aliimage/pinpoint-collector:1.6.1-SNAPSHOT
    - cd ..
    - cd web
    - mvn clean package docker:build -DskipTests
    - docker push $aliimage/pinpoint-web:1.6.1-SNAPSHOT
  only:
    - build